spring:
  application:
    name: api-gateway  # This name must match config files in config server
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  # Config Server connection
  config:
#    import: "configserver:http://localhost:8888"
    # Alternative format for newer Spring Cloud versions:
     import: "optional:configserver:http://localhost:8888"

  # Profile configuration
  profiles:
    active: default
