# Global configuration for all ByteBites microservices
# This file should be created at: src/main/resources/config-repo/application.yml

# Eureka client configuration (shared by all services)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# Actuator configuration (shared by all services)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Common logging configuration
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    olim.com: DEBUG

# Common application properties
bytebites:
  version: 1.0.0
  environment: development

# JWT configuration (shared by services that need JWT)
jwt:
  secret: mySecretKey12345678901234567890  # In production, use environment variable
  expiration: 86400000  # 24 hours in milliseconds

# Database connection pool settings (shared)
spring:
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000