# Auth Service specific configuration
# Save this as: ConfigServer/src/main/resources/config-repo/auth-service.yml

server:
  port: 8080

spring:
  application:
    name: auth-service

# JWT configuration for auth service
jwt:
  secret: mySecretKey12345678901234567890
  expiration: 86400000  # 24 hours

# Logging specific to auth service
logging:
  level:
    olim.com.authservice: DEBUG